// DO NOT EDIT THIS: This file was generated by the Pyrin Dart Generator
import 'package:result_dart/result_dart.dart';

import './types.dart';
import './base_client.dart';

class ApiClient extends BaseApiClient {
  ApiClient({super.baseUrl}) {
    url = ClientUrls(baseUrl);
  }

  late ClientUrls url;  
  
  AsyncResultDart<NoBody, ApiError> test(String bid, LelBody body, {RequestOptions? options}) async {
    final res = await request("POST", "/api/v1/test/$bid", options: options, body: body.toJson());
    return res.map((success) => NoBody());
  }
  
  AsyncResultDart<NoBody, ApiError> test2(FormDataType body, {RequestOptions? options}) async {
    final res = await requestForm("POST", "/api/v1/test", options: options, body: body);
    return res.map((success) => NoBody());
  }
}

class ClientUrls {
  ClientUrls(this.baseUrl);

  String baseUrl;
  
  String getFile() {
    return createUrl(baseUrl, "/file");
  }
  
  String test(String bid) {
    return createUrl(baseUrl, "/api/v1/test/$bid");
  }
  
  String test2() {
    return createUrl(baseUrl, "/api/v1/test");
  }
}
