// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api



func (c *Client) Test(bid string, body LelBody, options Options) (*any, error) {
	path := Sprintf("/api/v1/test/%v", bid)
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return Request[any](data, body)
}

func (c *Client) Test2(boundary string, body Reader, options Options) (*any, error) {
	path := "/api/v1/test"
	url, err := createUrl(c.addr, path, options.Query)
	if err != nil {
		return nil, err
	}

	data := RequestData{
		Url: url,
		Method: "POST",
		ClientHeaders: c.Headers,
		Headers: options.Header,
	}
	return RequestForm[any](data, boundary, body)
}

func (c *ClientUrls) GetFile() (*URL, error) {
	path := "/file"
	return c.getUrl(path)
}

func (c *ClientUrls) Test(bid string) (*URL, error) {
	path := Sprintf("/api/v1/test/%v", bid)
	return c.getUrl(path)
}

func (c *ClientUrls) Test2() (*URL, error) {
	path := "/api/v1/test"
	return c.getUrl(path)
}
