// DO NOT EDIT THIS: This file was generated by the Pyrin Golang Generator
package api

type LelBody struct {
	Username string `json:"username"`
	Password string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
}

type Test2Body struct {
	Id string `json:"id"`
	Name string `json:"name"`
	LastName string `json:"lastName"`
	Age intint `json:"age"`
}

