// DO NOT EDIT THIS: This file was generated by the Pyrin Typescript Generator
import { z } from "zod";

export const LelBody = z.object({
  username: z.string().optional(),
  password: z.string(),
  confirmPassword: z.string(),
});

export type LelBody = z.infer<typeof LelBody>;

export const Test2Body = z.object({
  id: z.string(),
  name: z.string(),
  lastName: z.string(),
  age: z.number(),
});

export type Test2Body = z.infer<typeof Test2Body>;

